# Generated by Django 5.0.6 on 2024-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casted_actors',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
