# Generated by Django 5.0.6 on 2024-05-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_casted_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='casted_actors',
            new_name='actors',
        ),
    ]
