# Generated by Django 5.0.6 on 2024-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_actors_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='casted_actors',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
